language: dart
sudo: required
dart:
  - stable
  - beta
  - dev
before_install:
  - nvm install node
  - node --version
before_script:
  - cd repo_support
  - dart pub get
script:
  - dart run tool/run_ci.dart
cache:
  directories:
    - $HOME/.pub-cache