name: tekartik_core_node
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_js_utils_interop:
    git:
      url: https://github.com/tekartik/js_utils.dart
      path: js_utils_interop
      ref: dart3a
    version: '>=0.1.0'
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
