name: tekartik_platform_node_test
description: Platform node
version: 0.3.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  tekartik_platform:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform
      ref: dart2_3
    version: '>=0.2.1'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart2_3
    version: '>=0.2.1'
  tekartik_platform_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: platform_node
      ref: dart2_3
    version: '>=0.2.1'
  path: '>=1.6.1'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  build_test: '>=0.10.8'
  process_run: '>=0.10.0+1'
  tekartik_platform_test:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_test
      ref: dart2_3
    version: '>=0.2.1'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3
dependency_overrides:
  tekartik_platform_node:
    path: ../platform_node
  # tekartik_build_node:
  #  path: ../../../tekartik/build_node.dart/packages/build_node
