name: tekartik_platform_node_test
description: Platform node
version: 0.3.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_platform:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform
      ref: dart3a
    version: '>=0.2.1'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart3a
    version: '>=0.2.1'
  tekartik_platform_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: platform_node
      ref: dart3a
    version: '>=0.2.1'
  path: ">=1.9.0"

dev_dependencies:
  test: ">=1.24.0"
  build_test: '>=0.10.8'
  process_run: ">=1.2.1+1"
  tekartik_platform_test:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_test
      ref: dart3a
    version: '>=0.2.1'
  # needed node dependencies
  build_runner: ">=2.4.13"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a

resolution: workspace
  # tekartik_build_node:
  #  path: ../../../tekartik/build_node.dart/packages/build_node
