targets:
  $default:
    sources:
      - lib/**
      - test/**
      - node/**
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - "node/**"
        options:
          compiler: dart2js

          # List any dart2js specific args here, or omit it.
          # dart2js_args:
          # - --checked