name: tekartik_http_node_test
description: http on node test
version: 0.4.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.6.0

dependencies:
  path: ">=1.9.0"
  fs_shim: ">=2.3.3+1"
  tekartik_http_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: http_node
      ref: dart3a
    version: '>=0.2.0'
  tekartik_http_test:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_test
      ref: dart3a
    version: '>=0.2.0'

  # node_io: '>=1.0.1+2'
  # node_io: any

dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.0+2"
  http_client_conformance_tests:
    git:
      url: https://github.com/dart-lang/http
      ref: master
      path: pkgs/http_client_conformance_tests
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart3a
    version: '>=0.1.0'
  tekartik_platform:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform
      ref: dart3a
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart3a
    version: '>=0.2.0'
  process_run: ">=1.2.1+1"
  # needed node dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

  http: any
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      ref: dart3a
      path: http
  tekartik_platform_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      ref: dart3a
      path: platform_node

resolution: workspace
  # fs_shim:
  #  path: ../fs
  # tekartik_fs_test:
#    path: ../../fs_shim.dart/fs_test

# node_io:
#   git:
#      url: https://github.com/tekartik/node-interop
#      path: node_io
#  node_io:
#    path: /media/ssd/devx/git/github.com/tekartik/node-interop/node_io
#  tekartik_platform:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform
#  tekartik_platform_node:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform_node
