targets:
  $default:
    sources:
      - "$package$"
      - "bin/**"
      - "node_example/**"
      - "lib/**"
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - bin/**
          - node_example/**
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          # dart2js_args:
          # - --checked