name: tekartik_platform_node
description: Platform node
version: 0.3.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.8.0

dependencies:
  tekartik_platform:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform
      ref: dart3a
    version: '>=0.2.1'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart3a
    version: '>=0.2.1'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  # node_io: '>=2.0.0'
  # node_interop: '>=2.0.0'
  pub_semver: ">=2.1.4"
  tekartik_core_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: core_node
      ref: dart3a
dev_dependencies:
  test: ">=1.24.0"
  tekartik_platform_test:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_test
      ref: dart3a
    version: '>=0.2.1'
  process_run: ">=1.2.1+1"

resolution: workspace
