name: tekartik_http_redirect_node
description: Node redirect.
version: 0.5.2
publish_to: none

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http
      ref: dart2
    version: '>=0.5.0'
  tekartik_http_io:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_io
      ref: dart2
    version: '>=0.5.0'
  tekartik_http_redirect:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_redirect
      ref: dart2
    version: '>=0.5.0'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
  args: any



dev_dependencies:
  dev_test: '>=0.13.2-dev.3'
  test: '>=1.2.0'
  build_runner: ">=0.9.0"
  build_test:
  # build_node_compilers: ">=0.2.2"
  # build_web_compilers: ">=0.4.2"
  process_run: '>=0.10.0+1'
  tekartik_app_node_build:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2
    version: '>=0.2.3'
dependency_overrides:
  tekartik_http_node:
    path: ../http_node
