name: tekartik_http_redirect_node
description: Node redirect.
version: 0.5.2
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http
      ref: null_safety
    version: '>=0.5.0'
  tekartik_http_io:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_io
      ref: null_safety
    version: '>=0.5.0'
  tekartik_http_redirect:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_redirect
      ref: null_safety
    version: '>=0.5.0'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: null_safety
  tekartik_http_node:
    git:
      url: git://github.com/tekartik/common_node.dart
      path: http_node
      ref: null_safety
  args: any



dev_dependencies:
  dev_test: '>=0.13.2-dev.3'
  test: '>=1.2.0'
  build_test:
  # build_node_compilers: ">=0.2.2"
  # build_web_compilers: ">=0.4.2"
  process_run: '>=0.10.0+1'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    git:
      url: git://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: null_safety
dependency_overrides:
  tekartik_http_node:
    path: ../http_node
  tekartik_fs_node:
    path: ../fs_node
  tekartik_platform_node:
    path: ../platform_node
