name: tekartik_fs_node
description: fs_shim on node
version: 0.4.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: '>=1.6.1'
  fs_shim: '>=0.11.0+3'
  node_interop: '>=1.0.3'
  node_io: '>=1.0.1+2'
  # node_io: any

dev_dependencies:
  pedantic: '>=1.4.0'
  test: ">=1.0.0"
  dev_test: any
  build_runner: '>=1.7.0'
  build_test: '>=0.10.8'
  build_node_compilers: ">=0.2.2"
  tekartik_fs_test:
    git:
      url: git://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart2
    version: '>=0.1.0'
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
      ref: dart2
  tekartik_platform_node:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_node
      ref: dart2
    version: '>=0.2.0'
  process_run: '>=0.10.0+1'

dependency_overrides:
  # fs_shim:
  #  path: ../fs
  # tekartik_fs_test:
  #  path: ../fs_test

# node_io:
#   git:
#      url: git://github.com/tekartik/node-interop
#      path: node_io
#  node_io:
#    path: /media/ssd/devx/git/github.com/tekartik/node-interop/node_io
#  tekartik_platform:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform
#  tekartik_platform_node:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform_node