name: repo_support
description: Repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  path:
  pub_semver:
  process_run: '>=0.10.3'
  test:
  dev_test:
  pedantic:
  tekartik_build_node:
    git:
      url: git://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: null_safety
  tekartik_lints:
    git:
      url: git://github.com/tekartik/common.dart
      ref: null_safety
      path: packages/lints
    version: '>=0.1.0'
dependency_overrides:
  # Temp
  # tekartik_app_node_build:
  #  path: ../../app_node_utils.dart/app_build