name: Run CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.dart }} / ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: repo_support
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            dart: stable
            node: 20
          - os: ubuntu-latest
            dart: stable
            node: 22
          - os: ubuntu-latest
            dart: stable
            node: 18
          - os: ubuntu-latest
            dart: beta
            node: 20
          - os: ubuntu-latest
            dart: dev
            node: 20
          - os: windows-latest
            dart: stable
            node: 20
          - os: macos-latest
            dart: stable
            node: 20
    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1.4
        with:
          sdk: ${{ matrix.dart }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: dart --version
      - run: dart pub get
      - run: dart run tool/run_ci.dart
